# Generated by Django 4.2.7 on 2023-11-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='beak_length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='finch',
            name='beak_width',
            field=models.FloatField(),
        ),
    ]
